openapi: 3.0.0
info: {}
paths: {}
components:
  parameters:
    jsonContentType:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        enum:
          - 'application/json'
    jsonAccept:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        enum:
          - 'application/json'
    authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      example: 'Bearer 2|BcDzBWZ7MczeYzuxJA68GOg4aujJCePXUCHoOCvY'
  schemas:
    Error422:
      type: object
      properties:
        message:
          type: string
          example: "The name field is required. (and 1 more error)"
        errors:
          type: object
          example:
            name: [ "The name field is required" ]
            other: [ "The other field is required" ]
    Error401:
      type: object
      properties:
        message:
          type: string
          example: "Unauthenticated."
    Error403:
      type: object
      properties:
        message:
          type: string
          example: "Only <role> can alter data."
    Error404:
      type: object
      properties:
        message:
          type: string
          example: "No query results for model [App\\Models\\<Model>] <id>"
    DataObject:
      type: object
      required:
        - data
      properties:
        data:
          type: array
    MediaResource:
      type: object
      properties:
        url:
          type: string
          example: "https://via.placeholder.com/400x400.png/0077ff?text=iure"
        meta:
          type: string
          example: "cover photo"
    BindingRequest:
      type: object
      properties:
        name:
          type: string
          example: "Hardback"
    BindingResource:
      type: object
      properties:
        id:
          type: integer
          example: 5
        name:
          type: string
          example: "Hardback"
        deleted_at:
          type: string
          example: "2023-03-13 01:21:26"
          required: false
          description: "Only shows up when a resource has been deleted"
    LanguageRequest:
      type: object
      properties:
        name:
          type: string
          example: "English"
        iso_639_1:
          type: string
          example: "en"
    LanguageResource:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: "English"
        iso_639_1:
          type: string
          example: "en"
        deleted_at:
          type: string
          example: "2023-03-13 01:21:26"
          required: false
          description: "Only shows up when a resource has been deleted"
    ItemTypeRequest:
      type: object
      properties:
        name:
          type: string
          example: "Light Novel"
    ItemTypeResource:
      type: object
      properties:
        id:
          type: integer
          example: 5
        name:
          type: string
          example: "Light Novel"
        deleted_at:
          type: string
          example: "2023-03-13 01:21:26"
          required: false
          description: "Only shows up when a resource has been deleted"
    PublisherRequest:
      type: object
      properties:
        name:
          type: string
          example: "VIZ Media"
        url:
          type: string
          example: "https://www.viz.com/"
        about:
          type: string
          example: "VIZ Media LLC is an American entertainment company headquartered in San Francisco, California, focused on publishing manga, distribution and licensing Japanese anime, films, and television series. It was founded in 1986 as VIZ LLC. In 2005, VIZ LLC and ShoPro Entertainment merged to form the current VIZ Media LLC, which is owned by Japanese publishing conglomerates Shueisha and Shogakukan, as well as Japanese production company Shogakukan-Shueisha Productions (ShoPro)."
        logo:
          type: string
          format: binary
    PublisherResource:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: "VIZ Media"
        url:
          type: string
          example: "https://www.viz.com/"
        about:
          type: string
          example: "VIZ Media LLC is an American entertainment company headquartered in San Francisco, California, focused on publishing manga, distribution and licensing Japanese anime, films, and television series. It was founded in 1986 as VIZ LLC. In 2005, VIZ LLC and ShoPro Entertainment merged to form the current VIZ Media LLC, which is owned by Japanese publishing conglomerates Shueisha and Shogakukan, as well as Japanese production company Shogakukan-Shueisha Productions (ShoPro)."
        logo:
          $ref: '#/components/schemas/MediaResource'
        deleted_at:
          type: string
          example: "2023-03-13 01:21:26"
          required: false
          description: "Only shows up when a resource has been deleted"
  responses:
    BadData:
      description: Missing / Incorrect data submitted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error422'
    Unauthenticated:
      description: Expired or Missing Bearer Token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401'
    Unauthorized:
      description: No permission (Editor/Admin Only Access)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error403'
    NotFound:
      description: Wrong object ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error404'
    Binding200:
      description: Successfull operation for Binding Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DataObject'
              - properties:
                  data:
                    $ref: '#/components/schemas/BindingResource'
    Language200:
      description: Successfull operation for Language Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DataObject'
              - properties:
                  data:
                    $ref: '#/components/schemas/LanguageResource'
    ItemType200:
      description: Successfull operation for ItemType Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DataObject'
              - properties:
                  data:
                    $ref: '#/components/schemas/ItemTypeResource'
    Publisher200:
      description: Successfull operation for Publisher Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DataObject'
              - properties:
                  data:
                    $ref: '#/components/schemas/PublisherResource'